on: [push]
jobs:
  test_outputs:
    name: Continuous Integration
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: create fixtures
        id: create_fixtures
        continue-on-error: true
        run: |
          Write-Host "Creating Fixtures"
      - name: create terraform
        id: create_terraform
        continue-on-error: true
        run: |
          Write-Host "Creating Terraform"
      - name: run tests
        id: run_pester_tests
        if: ${{ steps.create_terraform.outcome == 'success' && steps.create_fixtures.outcome == 'success' }}
        continue-on-error: true
        run: |
          Import-Module Pester
          $config = [PesterConfiguration]::Default
          $config.Run.Exit = $true
          Invoke-Pester -Configuration $config
        working-directory: ${{github.workspace}}/.github/workflows
      - name: destroy terraform
        id: destroy_terraform
        continue-on-error: true
        run: |
          Write-Host "Destroying Terraform"
      - name: destroy fixtures
        id: destroy_fixtures
        continue-on-error: true
        run: |
          Write-Host "Destroying Fixtures"
      - name: validation
        run : |
          if ($${{ steps.create_terraform.outcome == 'success' && steps.create_fixtures.outcome == 'success' }}) {
            Write-Host "Creating the resources succeeded"
          }

          if ($${{ steps.destroy_terraform.outcome == 'success' && steps.destroy_fixtures.outcome == 'success' }}) {
            Write-Host "Creating the resources succeeded"
          }
