on: [push]
jobs:
  test_outputs:
    name: Continuous Integration
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: create fixtures
        id: create_fixtures
        run: |
          echo '::set-output name=succeeded::true'
      - name: create terraform
        id: create_terraform
        run: |
          echo '::set-output name=succeeded::false'
      - name: run tests
        id: run_tests
        if: ${{ steps.create_fixtures.outputs.succeeded == 'true' }}
        run: |
          Write-Host "${{ steps.create_fixtures.outputs.succeeded }}"
      - name: run tests 2
        id: run_tests2
        if: ${{ steps.create_terraform.outputs.succeeded == 'true' }}
        run: |
          Write-Host "${{ steps.create_terraform.outputs.succeeded }}"
      - name: does it translate
        run: |
          if ($${{ steps.create_terraform.outputs.succeeded == 'true' && steps.create_fixtures.outputs.succeeded == 'true' }}) {
            Write-Host "All succeeded"
          } else {
            Write-Host "One failed"
          }

          if ($${{ steps.create_fixtures.outputs.succeeded == 'true' }}) {
            Write-Host "create_fixtures succeeded"
          } else {
            Write-Host "create_fixtures failed"
          }

          if ($${{ steps.create_terraform.outputs.succeeded == 'true' }}) {
            Write-Host "create_terraform succeeded"
          } else {
            Write-Host "create_terraform failed"
          }
    
      - name: run tests
        id: run_pester_tests
        if: ${{ steps.create_terraform.outputs.succeeded == 'true' && steps.create_fixtures.outputs.succeeded == 'true' }}
        continue-on-error: true
        run: |
          Import-Module Pester
          $config = [PesterConfiguration]::Default
          $config.Run.Exit = $true
          Invoke-Pester -Configuration $config
        working-directory: ${{github.workspace}}/.github/workflows
      - name: validation
        run : |
          <#
          if: ${{ steps.create_terraform.outputs.succeeded == 'false' || steps.create_fixtures.outputs.succeeded == 'false' }} {
            throw "failed to create resources."
          }

          Write-Host
          if ("${{ steps.run_pester_tests.outcome }}" -eq "skipped") {
            throw ""
          }
          #>
